//手机号响应
export const FORGETPWD_CHANGE_PHONE = 'FORGETPWD_CHANGE_PHONE';
//验证码响应
export const FORGETPWD_CHANGE_VCODE = 'FORGETPWD_CHANGE_VCODE';
//密码响应
export const FORGETPWD_CHANGE_PWD = 'FORGETPWD_CHANGE_PWD';
//button按钮
export const FORGETPWD_BUTTON_TRUE = 'FORGETPWD_BUTTON_TRUE';
export const FORGETPWD_BUTTON_FALSE = 'FORGETPWD_BUTTON_FALSE';
//验证码已发送
export const FORGETPWD_VCODE_TRUE = 'FORGETPWD_VCODE_TRUE';
//验证码发送失败
export const FORGETPWD_VCODE_FALSE = 'FORGETPWD_VCODE_FALSE';
//验证码倒计时
export const FORGETPWD_VCODE_COUNTDOWN = 'FORGETPWD_VCODE_COUNTDOWN';
//验证码发送重置
export const FORGETPWD_VCODE_RESET = 'FORGETPWD_VCODE_RESET';
//登录等待界面
export const ON_FORGETPWD_WAITING = 'ON_FORGETPWD_WAITING';
//取消等待
export const FORGETPWD_SHADOW_FALSE = 'FORGETPWD_SHADOW_FALSE';
//内容重置
export const FORGETPWD_RESET = 'FORGETPWD_RESET';










