//昵称响应
export const REGISTERDETAIL_CHANGE_NICKNAME = 'REGISTERDETAIL_CHANGE_NICKNAME';
//签名响应
export const REGISTERDETAIL_CHANGE_SIGNATURE = 'REGISTERDETAIL_CHANGE_SIGNATURE';
//设置性别
export const REGISTERDETAIL_SET_GENDER = 'REGISTERDETAIL_SET_GENDER';
//button按钮
export const REGISTERDETAIL_BUTTON_TRUE = 'REGISTERDETAIL_BUTTON_TRUE';
export const REGISTERDETAIL_BUTTON_FALSE = 'REGISTERDETAIL_BUTTON_FALSE';
//等待界面
export const ON_REGISTERDETAIL_WAITING = 'ON_REGISTERDETAIL_WAITING';
//取消等待
export const REGISTERDETAIL_SHADOW_FALSE = 'REGISTERDETAIL_SHADOW_FALSE';
//显示头像Android
export const REGISTERDETAIL_SHOW_IMG_ANDROID = 'REGISTERDETAIL_SHOW_IMG_ANDROID';
//显示头像IOS
export const REGISTERDETAIL_SHOW_IMG_IOS = 'REGISTERDETAIL_SHOW_IMG_IOS';
//错误信息
export const REGISTERDETAIL_ERROR_MESSAGE = 'REGISTERDETAIL_ERROR_MESSAGE';
//数据提交
export const REGISTERDETAIL_FALSE = 'REGISTERDETAIL_FALSE';













