//手机号响应
export const REGISTER_CHANGE_PHONE = 'REGISTER_CHANGE_PHONE';
//验证码响应
export const REGISTER_CHANGE_VCODE = 'REGISTER_CHANGE_VCODE';
//密码响应
export const REGISTER_CHANGE_PWD = 'REGISTER_CHANGE_PWD';
//button按钮
export const REGISTER_BUTTON_TRUE = 'REGISTER_BUTTON_TRUE';
export const REGISTER_BUTTON_FALSE = 'REGISTER_BUTTON_FALSE';
//验证码已发送
export const REGISTER_VCODE_TRUE = 'REGISTER_VCODE_TRUE';
//验证码发送失败
export const REGISTER_VCODE_FALSE = 'REGISTER_VCODE_FALSE';
//验证码倒计时
export const REGISTER_VCODE_COUNTDOWN = 'REGISTER_VCODE_COUNTDOWN';
//验证码发送重置
export const REGISTER_VCODE_RESET = 'REGISTER_VCODE_RESET';
//等待界面
export const ON_REGISTER_WAITING = 'ON_REGISTER_WAITING';
//取消等待
export const REGISTER_SHADOW_FALSE = 'REGISTER_SHADOW_FALSE';
//打开注册详情页
export const REGISTERDETAIL_TRUE = 'REGISTERDETAIL_TRUE';










